spring:
  application:
    name: Demo Project
  datasource:
    # driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testna2?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=CET
    name: Posavjetuj MySQL Connection
    username: root
    password: root
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
    database: MYSQL
    show_sql: true
    properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
  jackson:
    serialization:
      write_dates_as_timestamps: false
  liquibase:
    change-log: classpath:liquibase/master.xml
server:
  port: 8080

debug: false

jwt:
  secret: bXktY3VzdG9tLXNlY3JldC1rZXk=
  validityInMilis: 3000